import type { Metadata } from "next"
import "./globals.css"
import { cn } from "@/lib/utils"
import { ConditionalFooter } from "@/components/layout/conditional-footer"
import "@fontsource/poppins/400.css"
import "@fontsource/poppins/500.css"
import "@fontsource/poppins/600.css"
import "@fontsource/poppins/700.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/context/auth-context"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "light",
        "font-sans",
      )}
      style={{ colorScheme: "light" }}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col overflow-x-hidden">
        <AuthProvider>
          <div className="flex-1">{children}</div>
          <ConditionalFooter />
        </AuthProvider>
      </body>
    </html>
  )
}
